version: '3.8'

services:
  flask-app:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: python:3.11-slim
    container_name: cpb-app
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    working_dir: /app
    command: bash start.sh
    env_file:
      - .env
    restart: unless-stopped

  flask-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cpb-tunnel
    command: tunnel --url http://flask-app:5001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - flask-app
    restart: unless-stopped
